CREATE INDEX IDX_FAIXA_PEDIDO ON PEDCP01 (CAST(SUBSTRING(CAST(VDPEDCPE_NPED AS VARCHAR(12)),9,4) AS INT));
CREATE INDEX IDX_FAIXA_PEDIDO ON PEDIT01 (CAST(SUBSTRING(CAST(VDPEDIPE_NIT AS VARCHAR(12)),9,4) AS INT));
CREATE INDEX IDX_FAIXA_PEDIDO ON VDPEDFLC (CAST(SUBSTRING(CAST(VDPEDFLC_NPED AS VARCHAR(12)),9,4) AS INT));