DECLARE SET SMALLINT @NREMP = 0;
DECLARE SET BIGINT @NPED = 0;
DECLARE SET INT @OPERIDSIT = 0;

CREATE OR REPLACE VIEW VW_TM_APIOPERATION_CAPA 
AS 
SELECT
  VDPEDTMC_NPED ReferenceCode,
  VDPEDCPP_ERP_TERCEIRO AuthorizationId,
  CASE WHEN SUBSTRING(REPEAT('0',15-LENGTH(CAST(VDPEDTMC_CGC_CLI AS VARCHAR(15)))) || CAST(VDPEDTMC_CGC_CLI AS VARCHAR(15)) || REPEAT('0',15-LENGTH(CAST(VDPEDTMC_CGC_CLI AS VARCHAR(15)))) || CAST(VDPEDTMC_CGC_CLI AS VARCHAR(15)),10,4) = '0000' THEN 
         SUBSTRING(REPEAT('0',15-LENGTH(CAST(VDPEDTMC_CGC_CLI AS VARCHAR(15)))) || CAST(VDPEDTMC_CGC_CLI AS VARCHAR(15)),1,9) || SUBSTRING(REPEAT('0',15-LENGTH(CAST(VDPEDTMC_CGC_CLI AS VARCHAR(15)))) || CAST(VDPEDTMC_CGC_CLI AS VARCHAR(15)),14,2)
       ELSE
         REPEAT('0',14-LENGTH(CAST(VDPEDTMC_CGC_CLI AS VARCHAR(14)))) || CAST(VDPEDTMC_CGC_CLI AS VARCHAR(14))
  END customerid,
  VDPEDTMC_VLR_TOT_OPER amount,
  VDPEDTMC_VLR_DESC_OPER discount,
  VDPEDTMC_CHAVE_NFE validationkey,
  VDPEDTMC_DT_EMIS_NF invoicedate,
  VDPEDTMC_DT_VENC_TIT duedate,
  VDPEDTMC_XML_NF invoicexml
FROM
  VDPEDTMC 
INNER JOIN 
  VDPEDCPP ON VDPEDCPP_NREMP = VDPEDTMC_NREMP AND 
              VDPEDCPP_NPED = VDPEDTMC_NPED
WHERE
  VDPEDTMC_NREMP = @NREMP AND 
  (VDPEDTMC_NPED = @NPED OR @NPED = 0) AND 
  (VDPEDTMC_OPER_ID_STT = @OPERIDSIT OR @OPERIDSIT = 0);

DECLARE SET SMALLINT @NREMP = 0;
DECLARE SET BIGINT @NPED = 0;
    
CREATE OR REPLACE VIEW VW_TM_APIOPERATION_ITEM
AS 
SELECT
  VDPEDTMI_NPED ReferenceCode,
  VDPEDTMI_NR_PARC installmentnumber,
  VDPEDTMI_NOSSO_NR_BOLETO Number,
  VDPEDTMI_VLR_TIT amount,
  VDPEDTMI_VLR_DESC_TIT discount,
  VDPEDTMI_DT_VENC_TIT Duedate
  VDPEDTMI_DT_EMI_TITULO EMISSAO
  VDPEDTMI_NDUPL TITULO
FROM
  VDPEDTMI
WHERE
  VDPEDTMI_NREMP = NREMP AND (VDPEDTMI_NPED = @NPED OR @NPED = 0);