create function datetostr.DATETOSTR(DATE, varchar(20)) RETURNS varchar(20);
create function to_date.TO_DATE(varchar(20), varchar(20)) RETURNS DATE;
create function datetostr.TIMETOSTR(TIME, varchar(20)) RETURNS varchar(20);

DECLARE SET VARCHAR(18) @CODIGO_BARRA = '';
DECLARE SET SMALLINT @COMPRE_AGORA = 0;

CREATE OR REPLACE VIEW VW_CA_SALDO_ESTOQUE AS
SELECT  
  DATA_ESTOQUE,
  PRODUTO_CODBAR,
  PRODUTO_QTDUN,
  SALDO
FROM 
  SALDO_ESTOQUE_PORTAL
INNER JOIN
  CADPRD06 ON VDPRDPRD_CFAM = PRODUTO_FAM AND
              VDPRDPRD_NRO = PRODUTO_NRO   
WHERE
  VDPRDPRD_FLAG = 'A' AND
  (PRODUTO_CODBAR = @CODIGO_BARRA OR @CODIGO_BARRA = '') AND
  (VDPRDPRD_COMPRA_AGORA = @COMPRE_AGORA OR @COMPRE_AGORA = 0);
