create function datetostr.DATETOSTR(DATE, varchar(20)) RETURNS varchar(20);
create function to_date.TO_DATE(varchar(20), varchar(20)) RETURNS DATE;
create function datetostr.TIMETOSTR(TIME, varchar(20)) RETURNS varchar(20);

DECLARE SET VARCHAR(10) @CODIGO_CLIENTE = '';
DECLARE SET VARCHAR(1) @PARCEIRO = '';

CREATE OR REPLACE VIEW VW_SOL_PARCERIA_SINTETICO AS
SELECT 
  '' WERKS, 
  VDCLICLI_CODCLICIA KUNNR,
  CURDATE() DT_PROC,
  CASE WHEN VDCLIPRV_PARCEIRO_G01 = 1 THEN 'X' ELSE '' END PARC_COB,
  CASE WHEN VDCLIPRV_PARCEIRO_G01 = 1 THEN 'X' ELSE '' END PARC_POL,
  CASE WHEN VDCLIPRV_PARCEIRO_G01 = 1 THEN 'X' ELSE '' END PARC_RED,
  CASE WHEN VDCLIPRV_PARCEIRO_G01 = 1 THEN 'X' ELSE '' END PARC_DES,
  CASE WHEN VDCLIPRV_PARCEIRO_G01 = 1 THEN 'X' ELSE '' END PARC_FINAL,
  CASE WHEN VDCLIPRV_PARCEIRO_G01 = 1 THEN '241' ELSE '' END PARC_TAB,	
  '' PARC_PROC,
  1 PARC_STATUS
FROM
  VDCLPR06
INNER JOIN
  CADCLI06 ON VDCLICLI_REGI = VDCLIPRV_REGI AND
             VDCLICLI_NUM = VDCLIPRV_NUM
WHERE
  (VDCLICLI_CODCLICIA = @CODIGO_CLIENTE OR @CODIGO_CLIENTE = '') AND
  (CAST(VDCLIPRV_PARCEIRO_G01 AS VARCHAR(1)) = @PARCEIRO OR @PARCEIRO = '');
  
DECLARE SET VARCHAR(10) @CODIGO_CLIENTE = '';
DECLARE SET VARCHAR(10) @CODIGO_CATEGORIA = '';

CREATE OR REPLACE VIEW VW_SOL_PARCERIA_ANALITICO AS
SELECT 
  '' VSTEL, 
  VDCLICLI_CODCLICIA KUNNR,
  'COB' FLUXO,
  VDCLICLI_CODCLICIA CRI_COD,
  VDPRDGPA_CODCIA CTG_COD,
  CURDATE() DOCDAT,
  'X' CRI_STS,
  CASE WHEN VDCLIIFP_SIT = 1 THEN 'X' ELSE '' END CTG_STS,
  CASE WHEN VDCLIIFP_SIT = 1 THEN '241' ELSE '' END CRI_TAB,
  VDCLIIFP_NUMDIAS_PERDE DIAS_PERDE,
  CURDATE() PRCDAT,
  CURTIME() PRCHOR,
  '' PRCUSR
FROM
  VDCLIF06
INNER JOIN
  VDCLFS06 ON VDCLIFSP_COD = VDCLIIFP_CODFSP  
INNER JOIN
  CADCLI06 ON VDCLICLI_REGI = CAST(SUBSTRING(REPEAT('0',8-LENGTH(CAST(VDCLIIFP_CODCLI AS VARCHAR(8)))) || CAST(VDCLIIFP_CODCLI AS VARCHAR(8)) ,1,4) AS INT) AND
              VDCLICLI_NUM = CAST(SUBSTRING(REPEAT('0',8-LENGTH(CAST(VDCLIIFP_CODCLI AS VARCHAR(8)))) || CAST(VDCLIIFP_CODCLI AS VARCHAR(8)),5,4) AS INT)
INNER JOIN
  VDPRGP06 ON VDPRDGPA_GRPPAR = VDCLIIFP_GRPPAR AND VDPRDGPA_CODPRD = 0
WHERE
  (VDCLICLI_CODCLICIA = @CODIGO_CLIENTE OR @CODIGO_CLIENTE = '') AND
  (VDPRDGPA_CODCIA = @CODIGO_CATEGORIA OR @CODIGO_CATEGORIA = '');