// Apos aplicar estas views na Nova Cintra, deverá renomear as seguintes views do Portal antes de aplicá-las:
// CADCLI01 para VW_CLIENTE_PORTAL
// PEDCP01 para VW_CAPA_PEDIDO_PORTAL
// PEDIT01 para VW_ITEM_PEDIDO_PORTAL
  
CREATE OR REPLACE VIEW VW_CLIENTE_PORTAL AS
SELECT 
  A.* 
FROM 
  CADCLI01 A
INNER JOIN 
  (SELECT DISTINCT  
     VDCLIREG_COD
   FROM     
     CADREG01
   WHERE 
     VDCLIREG_NUMSUBEMPRESA_BW = <EMPRESA_BW>
  ) B ON B.VDCLIREG_COD = A.VDCLICLI_REGI;

CREATE OR REPLACE VIEW VW_CAPA_PEDIDO_PORTAL AS
SELECT 
  * 
FROM     
  PEDCP01
WHERE 
  CAST(SUBSTRING(CAST(VDPEDCPE_NPED AS VARCHAR(12)),9,4) AS INT) BETWEEN <SEQ_PED_INI> AND <SEQ_PED_FIM>;

CREATE OR REPLACE VIEW VW_ITEM_PEDIDO_PORTAL AS
SELECT 
  * 
FROM     
  PEDIT01
WHERE 
  CAST(SUBSTRING(CAST(VDPEDIPE_NIT AS VARCHAR(12)),9,4) AS INT) BETWEEN <SEQ_PED_INI> AND <SEQ_PED_FIM>;
